FROM docker.elastic.co/elasticsearch/elasticsearch:5.3.0

RUN ./bin/elasticsearch-plugin install https://github.com/MLnick/elasticsearch-vector-scoring/releases/download/v5.3.0/elasticsearch-vector-scoring-5.3.0.zip

